### ISSUE TITLE
Output tag to String variable

### ISSUE THREAD

**Issue by izogfif** [casid/jte#100]
It's possible to write HTML content into JSP variable like this:
```
<c:set var="fragment">
  <my:custom_tag1 param1="${param1}" param2="${param2}"/>
  some text
  <my:custom_tag2 param1="${param1}" param2="${param2}"/>
</c:set>
${Utils.processAndOutput(fragment)}
```
where `Utils.processAndOutput` is a static method that accepts `String` parameter, processes it and returns another `String`.
When converting this into JTE I'm getting
```
!{var fragment = @`@tag.customTag1(param1= param1, param2 = param2)
some text
@tag.customTag2(param1= param1, param2 = param2)
`;}
${Utils.processAndOutput(fragment)}
```
And since `fragment` variable here has type `jte.gg.Content`, it cannot be passed to `Utils.processAndOutput`. What's the workaround? Alternatively, is there a `toString()` or some other method that outputs current value of `fragment` variable? I mean can I write `${Utils.processAndOutput(fragment.someMethodThatReturnsString())}` in order to achieve the same result?

**Comment by casid** [comment]
That's right, you receive a `Content` here, because its String representation depends on where it is written to in the resulting template. The ideal way would be to pass that block to processAndOutput, if this is later used in another jte template.

If you really need a String, you could do something like this:

```java
StringOutput stringOutput = new StringOutput();
OwaspHtmlTemplateOutput htmlOutput = new OwaspHtmlTemplateOutput(stringOutput);
content.writeTo(htmlOutput);
String result = stringOutput.toString();
```

**Comment by izogfif** [comment]
Yes, I really need a string. There are many code blocks similar to the one I mentioned in my first message where contents of multiple tags is rendered into a string, stored inside a variable (declared via `<c:set/>` tag), and later this variable passed to method in the same .tag or .jsp file.

Could consider adding to `Content` interface a (probably, prefixed with `default` keyword) method `.renderAndGetString()` (or `.renderToString()` or simply override `.toString()` method, or come up with some better-named method)? This way I'll be able to write
```
!{var fragment = @`@tag.customTag1(param1= param1, param2 = param2)
some text
@tag.customTag2(param1= param1, param2 = param2)
`.renderAndGetString();}
`${Utils.processAndOutput(fragment)}`
```
and it JSP code conversion will go easier and .jte code will be functionally equivalent to JSP one.
Also, JSP converter should generate this kind of code when variable is set not via `<c:var name="varName" value="${value}"/>` but via `<c:var name="varName">${value}</c:var>`).

**Comment by casid** [comment]
No, there's a good reason `Content` does not have a `renderToString` method, since this really is a footgun when it comes to output escaping. When used in jte, the developer does not have to think about in which slot a `Content` block is rendered to apply correct escaping manually. Instead, output escaping is applied depending on what slot in the HTML the output is written to. Any `renderToString` has a huge potential to circumvent this and open up the HTML page to XSS vulnerabilities.

Right now the conversion is a bit cumbersome, but at least programmers will have to think about what they're doing with that String. What is `Utils.processAndOutput(String fragment)` doing? My recommendation would be to overload this method and handle the `Content` block conversion there, in Java: `Utils.processAndOutput(Content fragment)`.

**Comment by izogfif** [comment]
> and open up the HTML page to XSS vulnerabilities

That is, if HTML rendering is done with `ContentType.Html`. Which isn't always possible. In my case when writing tag attributes using tag call:
```
<a class="link-class"
     @tag.printLinkAttributes(attributeProvider = obj)
>Link text</a>
```
When I tried to use `ContentType.Html` I got errors, therefore I had to resort to using `ContentType.Plain` and `Utils.escapeHtml` everywhere.
I see your reasoning. Thanks. Gotta use some utility function to squeeze `String` out of `Content`.
