### ISSUE TITLE
JSP conversion: closing tag isn't being converted

### ISSUE THREAD

**Issue by izogfif** [casid/jte#103]
Probably should be fixed together with issue #99.
When converting JSP tag that has body, JSP converter doesn't replace tag end (probably because it just does simple find and replace in JSP code).
Example
```
<my:tag param="${value}">
  <div>Hello, ${fn:escapeXml(userName)}</div>
</my:tag>
```
Conversion yields
```
<jte:jte jte="tag/my/tag.jte" param="${value}">
  <div>Hello, ${fn:escapeXml(userName)}</div>
</my:tag>
```
(note the last line, it should have been converted to `</jte:jte>`.

**Comment by casid** [comment]
I got away with a string replace for this issue. #99 is a lot tougher though, since for that you'd have to understand the JSP. The converter does exactly that for the single tag that is converted. I'm afraid if we'd analyze all other jsps for usage search, conversion might become slower.

Luckily the JSP project I plan to convert has a consistent usage of taglib prefixes, so the incentive to implement #99  for me isn't very high. I'm happy to review / merge a PR if you want to give it a try though.

**Comment by izogfif** [comment]
I'd suggest to add recursive / nested tag call in test list. It's possible to call tag from within itself. For example, to output tree-like structure or content wrappers:
```
<my:wrap frameColor="${mainColor}">
    main content title
    announcement of nested content
    <my:wrap frameColor="${secondaryColor}">
        nested content
    </my:wrap>
</my:wrap>
```
