### ISSUE TITLE
Idea: type-safe access to templates from code

### ISSUE THREAD

**Issue by davidkron** [casid/jte#114]
As jte already has great support for type-safe templates, I think another step to improve the library even more, could be to improve the type-safety also on the caller site.

What I mean is something like the Play framework currently does:
https://www.playframework.com/documentation/2.8.x/ScalaTemplates#Overview

The template can be rendered from the code using type-safe (generated?) classes to reference templates and also the templates' typed parameters:
```
val content = views.html.Application.index(c, o)
```

**Comment by casid** [comment]
@davidkron jte already supports this, but there are some drawbacks. 

You'd need to configure maven/gradle to only generate Java sources only: https://github.com/casid/jte/blob/master/DOCUMENTATION.md#using-the-application-class-loader-since-120

Those generated files would become part of your application sources. To render a template, you'd just call its static render method. For example, if your template would be `index.jte`:

```java
var output = new StringOutput();
JteindexGenerated.render(output, param1, param2);
```

In case of `ContentType.Html` it's a bit more complicated:

```java
var output = new StringOutput();
JteindexGenerated.render(new OwaspHtmlTemplateOutput(output), null, param1, param2);
```

The output needs to be an instance of `HtmlTemplateOutput` and in case an interceptor is used it'd need to be passed as well (in the example above that's the `null` parameter).

The biggest drawback I've experienced with such a solution is that hot reload doesn't work for all changes. It then has the same limitations as all other java classes.

**Comment by casid** [comment]
I'm closing this as informative. Feel free to reopen though, if something's unclear.
