### ISSUE TITLE
Calling JTE template with multiple parameters

### ISSUE THREAD

**Issue by a1730** [casid/jte#120]
Is there a way to call a jte template with multiple parameters from Java without using a Map? We are migrating from Jsp land and looking for something like jsp:param.  We are reluctant to use ``render(,Map<String,Object>,)`` because we want to preserve type safety in our templates. The benefits of compile time static type analysis is one of the reasons we are trying to move away from jsp/pebble templates ...

What are we missing?

Thank you for a fantastic template engine.

**Comment by casid** [comment]
Welcome @a1730 and thank you for the heads up!

Unfortunately `render()` calls are dynamic and not type safe. This is a compromise made for hot reloadability during developement. Personally, I usually pass a context object instead of a map to mitigate this.

For instance, when rendering a page:

```java
public class WelcomePage {
   // page attributes
}
```

```html
@param WelcomePage page

${page.getFoo()}
${page.getBar()}
```

Then, there's one place of dynamic dispatch, when you render the template:

`templateEngine.render("welcome-page.jte", new WelcomePage(), out);`

With the IntelliJ plugin installed, all changes to `WelcomePage` will be picked up and available in the template. As long as the contract "welcome-page.jte uses class WelcomePage" is valid, there won't be any surprises.

Are you evaluating to migrate from JSP? If so, did you already have a look at the [JSP to jte convert](https://github.com/casid/jte/tree/master/jte-jsp-converter)?

**Comment by a1730** [comment]
Hi @casid,

Thank you for the fast response - as usual.
We figured that ``render(?,Object,?)`` will rear its ugly head:smile:
Actually, what you proposed is we have been doing -sorta, we created a JteContext which is currently a marker interface that is implemented by classes passed to render but we wanted to ensure that we are not duplicating the work that you have already done to render a template with multiple parameters. Our motivation for naming thigs comes from Java [JEP 369,](https://openjdk.java.net/jeps/359); we have drunk the coolaid that a central aspect of Java's philosophy is that names matter. WelcomePage would have to implement JteContext in our environment.
However, it is comforting to know that we are not missing a direct route for using multiple parameters and we will continue to use JteContext in our code base. 

It is a shame that TemplateEngine is a final class -we would have gladly changed [render](https://github.com/casid/jte/blob/e7c748f977796a758dde0a08a8f78f274a5639be/jte-runtime/src/main/java/gg/jte/TemplateEngine.java#L210) render to ``public void render(String name, JteContext param, TemplateOutput output) `` and remove the Intellij rule eliminating render(,Map,.) proposal.

Thank you.
PS: we are using JSP to jte convert on some of our migrations. JTE's ease of use and missing straight forward documentation makes it our second choice to manual conversion.

**Comment by casid** [comment]
Hey @a1730,

thanks for the detailled info! It looks we have quite the same philosophy to do things in Java. I'm also enforcing the usage of a context object in my projects through composition. E.g. for rendering pages no one knows the actual `TemplateRenderer` instance ;-)

```java
public final class PageRenderer {
   private final TemplateEngine templateEngine = initTemplateEngine();

  public void render(Page page, HttpServletResponse response) {
    Utf8ByteOutput output = new Utf8ByteOutput();
    templateEngine.render(page.getTemplate(), page, output);
   
   // ...
  }
}
```

In case jte is used for other aspects like mails (usually with a different template root):

```java
public final class MailRenderer {
   private final TemplateEngine templateEngine = initTemplateEngine();

  public String render(Mail mail) {
    StringOutput output = new StringOutput();
    templateEngine.render(mail.getTemplate(), mail, output);
   
   // ...
  }
}
```
