### ISSUE TITLE
Question: What is the best way to use translations (i18n) in templates?

### ISSUE THREAD

**Issue by finke-ba** [casid/jte#127]
Hello @casid! I'm looking for a solution for internationalisation in templates.
The obvious way is to add one field to the template model with map(key: translation_key, value: translated_value).
This looks very simple, but I have to add this map to all my models and add some code to my TemplateRenderer class(which handles logic for generating templates in the corresponding formats like jpg and pdf).

Another option is to use something like [MessageSource](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/MessageSource.html), but this requires support from the library.

So, what do you think about internationalisation support in jte?

**Comment by casid** [comment]
Welcome @finke-ba!

jte has no built in localization support, mainly because localization really is very framework specific. And ideally you could use the same tooling you use in the rest of your code in jte as well :-)

There's a LocalizationSupport interface that helps with connecting your framework to jte. The interface mainly takes care about output escaping during localization.

I usually access the localization facilities through a ThreadLocal, but it would also be possible to add that localizer as template parameter. Here's a rough scetch of the idea:
https://github.com/casid/jte/issues/49#issuecomment-774756473

Hope this helps!

**Comment by finke-ba** [comment]
Thank you very much for such a rapid and detailed answer!
I was thinking about using some external class inside template, but this idea came to me after I asked the original question and I wan not sure about details like  ThreadLocal and return type gg.jte.Content :)
So thank you very much for your static method example, at the moment this is my favorite option as I can encapsulate all the localization logic in one place and not change existing code.

It would be great if information on how to do something similar would be in the documentation and it would be especially useful to see an example with ThreadLocal, so as not to leave room for errors that can ruin the performance and validity of the data.

What do you think about adding this to the documentation?

**Comment by casid** [comment]
That's a really good suggestion! I added a [localization chapter](https://github.com/casid/jte/blob/master/DOCUMENTATION.md#localization) to the documentation.

Let me know if this helps, or if anything is missing.

**Comment by finke-ba** [comment]
This is a very good and detailed description!
I have no other questions on this topic, I think we can close this issue.
Thank you so much for such a great job on the library and with the community!
