### ISSUE TITLE
Invalid class path in single spring-boot jar

### ISSUE THREAD

**Issue by burashov** [casid/jte#128]
With the following configuration and **spring-boot executable single jar** jte is unable to locate packages gg.jte.* when trying to compile templates.

` CodeResolver codeResolver = new DirectoryCodeResolver(Path.of(root));
            return TemplateEngine.create(codeResolver, Path.of(classDirectory), ContentType.Html, gg.jte.Content.class.getClassLoader());`

The problem is in method ClassUtils.resolveClasspathFromClassLoader() as it is incorrectly resolves the classpath

p.s. The workaround for me is to use compiled templates:

`return TemplateEngine.createPrecompiled(ContentType.Html);`

and maven jte plugin

          <plugin>
                <groupId>gg.jte</groupId>
                <artifactId>jte-maven-plugin</artifactId>
                <version>1.11.4</version>
                <configuration>
                    <sourceDirectory>src/main/resources/templates</sourceDirectory> 
                    <targetDirectory>target/classes</targetDirectory> 
                    <contentType>Html</contentType>
                </configuration>
                <executions>
                    <execution>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>precompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by casid** [comment]
Hi @burashov!

for production build precompiled templates as you did it is awesome and the most secure way!

For local development it would be sad if hot reloading isn't working for you. Maybe this spring boot example project helps, especially the template renderer setup:

https://github.com/casid/jte-spring-boot-demo/blob/master/src/main/java/gg/jte/demo/TemplateRenderer.java

I guess what you get is a `ClassNotFoundException`, which indicates some class loading problem. Can you try to pass the ClassLoader of your own application's class ClassLoader instead of  `gg.jte.Content.class.getClassLoader()`, like in the demo repository.

Hope this helps!

**Comment by burashov** [comment]
for single executable jar protocol is JAR, not file...

![image](https://user-images.githubusercontent.com/17797757/150405676-250aa093-3aa9-4c1b-8589-8dbc193799e9.png)

**Comment by casid** [comment]
Thanks for clarifying! Sorry, I didn't carefully read the issue title, where you said it is about a single executable jar :-)

Glad you got hot reload going during development!

That being said, I see two options to improve this:

- Throw an error in this case with information about how to use precompiled templates for executable builds
- Try to parse the jar for more libs (I think I've seen this done in a few other libs)

I have a tendency to option 1), but I'm not sure if we can always get this correct. I think it would be a good idea to inform users of the lib better why precompiled templates are useful for production builds. This is quite different to other template engines and quite a key feature of jte to protect you from runtime exceptions in favor of compile time exceptions.
