### ISSUE TITLE
improve typesafe API experience

### ISSUE THREAD

**Issue by edward3h** [casid/jte#131]
I wanted to get this on your radar though I can't guarantee I'll actually work on it any time soon.

I like JTE for being able to pre-generate templates into Java classes. I've been thinking about how to use them in a typesafe way. 

Given a template:

_hello.jte_

```
@param String message
@param int count

Hello, ${message}
Count is ${count}
```

Then my Java code should be able to access it by name, give parameters and render it. Maybe something like this:

_MyClass.java_

```
var counter = 1;
templateFactory.hello("world", counter++).render(output);
```

This involves a factory class being generated along with the templates. It can be made available via dependency injection or a static method if you aren't using DI. The underlying TemplateEngine is hidden behind this facade.

**Comment by casid** [comment]
@edward3h that should work with hot reload as long as the template parameters used by the Java program don't change. But at that point a program restart would be required without such a facade as well.

For the next jte version there's gonna be a change, that the `@tag` and `@layout` special handling is removed for a more general `@template` keyword. This allows to call any template:
https://github.com/casid/jte/pull/126

So users may want to have an option, what templates are exposed through such a facade.

**Comment by nedtwigg** [comment]
I built and maintained a site using [rocker](https://github.com/fizzed/rocker) for a few years, and I've been really happy with it, except it doesn't have an IDE plugin (https://github.com/fizzed/rocker/issues/12). I took a look at migrating to jte just for the IDE plugin, and for me I have found that JTE is missing a few typesafe pieces. A feature-union of the two projects would be a dream!

With rocker, every template `main.html` creates 

```
public class main extends DefaultRockerModel {
  public static main template(String param1, POJO otherParam) {
        return new main()
            .param1(param1)
            .otherParam(otherParam);
    }

    @Override
    protected DefaultRockerTemplate buildTemplate() throws RenderingException {
      return new Template(this)
    }

    static public class Template extends DefaultRockerTemplate {
      // does the actual rendering
   }
}
```

The special thing here is that you get a `main` POJO which holds all the data of the template. You get compile errors if a template is used wrong. And the other thing is that you can tell the Rocker compiler that instead of `DefaultRockerModel` and `DefaultRockerTemplate`, you want to use `CustomRockerModel` or `CustomRockerTemplate`.

By using a custom template class, you can add functions which are available to use inside your templates. For example, every template in my project has access to a `Map<String, String> flash()` method which is auto-populated with data from a session cookie, so that you can just do `alertError()` or `alertSuccess()` to get a `<div class="alert"` whenever appropriate.

And by using a custom model class, you can use your web framework to inject data into the template (e.g. to make `flash()` etc. work).

Anyway, both projects are great. Not sure if it's easier to write an IDE plugin for rocker, or to add customizable model and template classes to `jte`. But I think rocker has a great thing going in its dataflow where Model classes instantiate Template classes, and you can customize the Model and Template base classes.

**Comment by casid** [comment]
Welcome @nedtwigg and thanks for sharing!

At least for jte the most significant amount of work went into the IntelliJ plugin. We also cheated a little bit by making the jte syntax as IDE friendly as possible. Which was possible as we created both from scratch at the same time.

That being said, with jte you can get almost all Rocker features by using plain Java. Personally, I have the convention to use one model per template. Your example would then look like this:

```java
public class MyModel {
   public String param1;
   public POJO otherParam;
}
```

```html
@param MyModel model

<div>${param1}, ${otherParam.foo}</div>
```

The template then has just one model parameter. Adding more data to the model is very easy and doesn't require a change to the template. The only downside is, that you must make sure once that the model matches the template. In practice this hasn't caused me trouble so far, since model and template are created once and after that all changes/refactorings are picked up by the IDE. What I also really like about this, is that the model is a pure data structure and not polluted by framework specific stuff.

For session related data there are currently two options right now. Pass the Session object to every template that needs it, or to use a ThreadLocal. I'm personally using the latter :-). There's an example [in the localization documentation](https://github.com/casid/jte/blob/main/DOCUMENTATION.md#localization). Instead of a HashMap, I'm using type-safe accessors on that session object.

My productivity with those two approaches combined is pretty good, especially the IDE refactoring support is a massive help. 

At my workplace, our frontend devs are currently migrating from JSP to jte. It is a pretty big enterprisy project, so the migration is done by applying the strangler pattern and migrating one leaf at a time, using this [semi-automatic converter](https://github.com/casid/jte/tree/main/jte-jsp-converter). In case you decide to migrate to jte, depending on the size of your project, a rocker to jte converter might be worth it.

**Comment by nedtwigg** [comment]
> making the jte syntax as IDE friendly as possible

That was smart! I'm experimenting with using [kotlinpoet](https://github.com/square/kotlinpoet) to generate a Kotlin model class for every template by parsing only the imports and args of the templates. The generated models all share a base class where I can use whatever methods related to thread locals etc. Main advantage is we get null-safety when we're calling them, but without the IDE hiccups that Kotlin integration is currently facing.

**Comment by edward3h** [comment]
I've been working on something for this BTW.

**Comment by agentgt** [comment]
Well FWIW my templating language has the idea that the "template is the contract".

https://github.com/jstachio/jstachio

For example a template is always tied to a model object that you annotate with `@JStache`.

While it is type-safe its unlikely I will ever be able to provide an IntelliJ plugin for java completion so JTE has it beat there but otherwise I think JStachio is superior particularly in the "template is the contract model per template" approach (but I am biased).

So for @casid template you could do

```java
@JStache(template = "{{param1}} {{POJO.someFieldOrMethodOnPOJO}}")
public class MyModel {
   public String param1;
   public POJO otherParam;
}
```

You can inline templates or have them on the filesystem (can you inline templates with JTE?). No special build plugins needed all is done with the compiler.

**Comment by casid** [comment]
Thanks for sharing @agentgt.

> can you inline templates with JTE?

No, that's not possible with jte currently, although you could write a code resolver that does this. But IntelliJ would not understand this and you'd be back to plain strings.

> so JTE has it beat there but otherwise I think JStachio is superior

I think this comes down to a matter of taste. It's good to have so many templating choices, so that there's a good fit for everyone.

**Comment by agentgt** [comment]
> I think this comes down to a matter of taste. It's good to have so many templating choices, so that there's a good fit for everyone.

I agree particularly if your original templates were JSP then Jte and Rocker are a good fit!

It was just playful arrogant humor :)

**Comment by casid** [comment]
This was finally released today, together with jte 3 :-)
