### ISSUE TITLE
Template imports for shorter template calls

### ISSUE THREAD

**Issue by casid** [casid/jte#141]
Template calls can be quite verbose, because they are always done by fully qualified name.

I would be nice to have an import for templates, like there is an import for classes in Java.

Proposed solution:

```html
@templateimport my.components.test-component

@test-component(value = "foo")
@test-component(value = "bar")
```

Would be equivalent to:

```html
@my.components.test-component(value = "foo")
@my.components.test-component(value = "bar")
```

As always, the trickiest part will be the IntelliJ plugin.

**Comment by casid** [comment]
This feature would make the IntelliJ plugin quite a bit more complicated.

For better usability with template calls, the IntelliJ plugin got much better auto-complete over all templates in the jte root directory, so for writing there's not a big difference anymore without this feature.

Readability without this feature is more verbose, but I'm unsure if this is really a bad thing.

This won't be worked on anymore.

**Comment by dzikoysk** [comment]
Hey, did you get to the point with this PR where you've touched IJ plugin, and it indeed turned out to be quite problematic? I'm curious, because the current approach does not scale that good with a bigger, component based project - especially with some extra nested levels of directories. Some sort of `@include component.group.feature.CoolComponent` would be kinda cool.

**Comment by casid** [comment]
Yes, it did become more complicated. We also have a deep, nested component structure at work, and the better auto-complete did help a lot.
