### ISSUE TITLE
Is jte supported with Apache Groovy?

### ISSUE THREAD

**Issue by fithisux** [casid/jte#178]
The site talks only about Java/Kotlin.

**Comment by casid** [comment]
I'm not a Groovy user, so I haven't tried using jte on a Groovy project. However, I believe it should work.

What the website is mostly about, is that plain Java or Kotlin can be used for logical expressions within the templates, instead of learning a new language just for that (as done by other template engines). In theory, this should be possible for Groovy as well (similiar to the [jte-kotlin](https://github.com/casid/jte/tree/main/jte-kotlin) module.

**Comment by fithisux** [comment]
Thank you very much. I need to experiment then.

**Comment by edward3h** [comment]
Hi, I'm a fan of JTE and Groovy - but I probably wouldn't use them together.

For Groovy I have used [MarkupBuilder](https://docs.groovy-lang.org/latest/html/api/groovy/xml/MarkupBuilder.html) to generate HTML. It's more Groovy style, but not so much like HTML with some embedded code.

The main benefit that attracted me to JTE was the ability to precompile the templates into Java classes, making it efficient to include them in GraalVM native-image. Groovy can't be turned into a native-image so that part isn't useful.

_Disclaimer: some people have managed to make native-images from very limited Groovy programs but it's a lot of work._

**Comment by fithisux** [comment]
> The main benefit that attracted me to JTE was the ability to precompile the templates into Java classes, making it efficient to include them in GraalVM native-image. Groovy can't be turned into a native-image so that part isn't useful.

Very useful comment.  Who knows, sometimes.
