### ISSUE TITLE
UTF-8 output performance

### ISSUE THREAD

**Issue by agentgt** [casid/jte#225]
Hi @casid I have been benchmarking my templating engine to be used in TechEmpowers benchmark (Jooby) which requires UTF-8 output with non latin-1 characters.

https://github.com/agentgt/template-benchmark

https://github.com/agentgt/template-benchmark/raw/utf8/results-utf8.png

The three templating engines that are able to do pre-encoding are JStachio (mine), JTE, and Rocker.
The also happen to be the fastest templating engines in the Java ecosystem for String output.

I cannot figure why JTE performs that much worse than Rocker and JStachio. I made sure to `setBinaryStaticContent` both in Maven and in Java (I know that is working because if I turn that off it gets far worse). 

Perhaps the custom Utf8Output is the culprit? Did you benchmark it? Both JStachio and Rocker don't bother doing all the chunking logic you have.

My other guess it is the escaping of which I turned on (all three have escaping turned on for this benchmark as TechEmpower requires it).

https://github.com/agentgt/template-benchmark/blob/utf8/src/main/java/com/mitchellbosecke/benchmark/JteUtf8.java

**Comment by casid** [comment]
Thanks for reporting @agentgt!

> I have been benchmarking my templating engine to be used in TechEmpowers benchmark (Jooby) which requires UTF-8 output with non latin-1 characters.

String can represent non latin-1 characters. The motivation is rather to save time from encoding static template parts to UTF-8 only once, right? I found this part of the README a bit confusing.

I'm not at my dev pc right now, but your jte setup looks correct. I'll have a closer look this weekend.

`Utf8Output` aims to avoid holding a big byte array containing the entire response data in memory. Instead it references the big static chunks and creates little dynamic ones on the fly. Those chunks are then passed one by one to the output stream of the web server. In your benchmark the result is a big byte array, so I imagine in this case `Utf8Output` introduces some overhead over just writing everything into a byte array.

**Comment by agentgt** [comment]
> String can represent non latin-1 characters. The motivation is rather to save time from encoding static template parts to UTF-8 only once, right? I found this part of the README a bit confusing.

Yeah the readme sucks ass as I wrote it very quick but the ultimate goal is to output UTF-8 which is not a Java String its a byte representation. Yes Java Strings can represent UTF-8 but most platforms allow you to write direct bytes. So yes this is about saving time.

String.getBytes() is insanely fast provided every single character is latin1 but in the real world that is not the case even here in the US as people use emojis.

That is what JStachioString in the benchmark diagram is doing. Its just the regular string benchmark with getBytes(). I guess I could have called it "JStachioGetBytes". I suppose I could put Rocker and JTE as well but the you can basically look at the original String benchmark as getBytes() will be the same overhead for all the tests.

> Those chunks are then passed one by one to the output stream of the web server. In your benchmark the result is a big byte array, so I imagine in this case Utf8Output introduces some overhead over just writing everything into a byte array.

All three implementations are designed in a similar manner. 
For example see Rockers: https://github.com/fizzed/rocker/blob/master/rocker-runtime/src/main/java/com/fizzed/rocker/runtime/ArrayOfByteArraysOutput.java

Besides I tried:

```java
    @Benchmark
    public Object benchmark() throws IOException {
        Utf8ByteOutput output = new Utf8ByteOutput();
        //ByteBufferedOutputStream stream = new ByteBufferedOutputStream(8 * 1024);
        templateEngine.render("stocks.jte", items, output);
        //output.writeTo(stream);
        //return stream.toByteArray();
        return null;
    }
```

So that Jte would not have to copy its internal buffers in Utf8Output and both JStachio and Rocker still outperform with some margin and those are actually getting the data out.

My guess is it is the OWasp escaping. Perhaps you have a simpler escaping implementation? However IIRC even when I had PlainText turned on the other two still beat JTE but I might be wrong.

**Comment by casid** [comment]
Hi @agentgt, I did some profiling today and I think you are correct. Quite some time is spent in the OWASP Java Encoder. It's not that easy to replace though, since jte doesn't do a general purpose escaping, but escapes differently depending on what template slot the content is rendered. For that, the methods in OWASP Java Encoder are very handy and battle tested. However, the OWASP Java Encoder is currently the only reason why the `TemplateOutput` interface needs to provide a `Writer` (for performance reasons), which is quite ugly and makes all implementations harder than they needed to be. So I'll keep a look if it is feasible to replace it with something else.

I also created a new class `Utf8ByteArrayOutput` (https://github.com/casid/jte/commit/e397525245bb80a9c363e4a98fa7ab370bce5b46). In case a byte array with the entire output is needed, this is faster than the existing `Utf8ByteOutput`.

**Comment by agentgt** [comment]
I wonder if there are some things I can do to make the test more fair especially since I think it is a kick ass feature.

I contemplated doing context sensitive escaping for JStachio but it was too much of an API change for me so I stayed with Mustache's default.

Perhaps we can alter the tests to require proper escaping of HTML attributes as a start. I know it is doing more than that but that would be a first step. Rocker and JStachio will just have to call some function to do it.

**Comment by casid** [comment]
I don't think you need to do something about the benchmark. It covers the most important escaping case, for other cases jte won't be any faster since it uses the same implementation there as well. Currently jte is slower than Rocker/JStachio in this regard and that's what benchmarks are meant to show.

I'll soon release a version with the new `Utf8ByteArrayOutput`, this should improve the benchmark a little bit, if used there :-)

**Comment by casid** [comment]
@agentgt We released jte 3 today with a lots of performance improvements in UTF-8 output and HTML encoding. I'll send you a PR for your benchmark in a few seconds.

Thank you for reporting this issue and your help to make jte faster!
