### ISSUE TITLE
Syntax proposal - @for @else

### ISSUE THREAD

**Issue by bohdan-shulha** [casid/jte#226]
Hi @casid ,

Thank you for creating great product. I enjoy using it every day!

I have a proposal to improve a little bit syntax of the template engine.

It is often happening that you need to iterate over list of items and display some message if there are no items at all.

Of course, it is achievable as of today via standalone `@if`, but what if we add `@else` construct to `@for` itself? It will give a little bit more visibility. Also, this way we wouldn't need to remember whether it is `.size()`, `.length` or other kind of sizing attribute/method of some iterable to create a fallback message.

```
<table>
  <tr>
    <td>Item</td>
    <td>Qty</td>
  </tr>
  @for(var item : groceryList)
    <tr>
      <td>${item.getName()}</td>
      <td>${item.getQuantity()}</td>
    </tr>
  @else
    <tr>
      <td colspan="2">You have forgotten your groceries list at home!</td>
    </tr>
  @endfor
</table>
```

I have been using it some time ago in Django (or Laravel's Blade, can't remember where exactly) and I find this feature useful.

**Comment by casid** [comment]
Welcome @bohdan-shulha!

Thank you for the heads up and for your suggestion. Your proposed syntax reads very nice.

However, this is close to impossible to implement with jte. The `@for` expression can be any valid Java/Kotlin code, for instance something like `@for(var i = 0; i < 10; i++)`. Currently, the jte compiler does not try to parse and understand those Java/Kotlin blocks, but relies upon the Java/Kotlin compiler to detect invalid code. For this feature however, we'd need to try to parse and understand the `@for` expression in order to generate the else block. This would introduce some kind of magic that I want to avoid.

**Comment by kelunik** [comment]
@casid We don't need to parse and understand the expression. All we need is an automatic tracking boolean variable that's automatically set to true in every loop iteration.

We however likely can't use else, because it'll conflict with if / else if an if is nested inside for.

**Comment by casid** [comment]
True, but that is still quite hacky. We need a boolean that doesn't conflict with user variables and keep track of nested for loops. It introduces a new way to do the same thing that can already be done with `@if` and a new keyword that users need to remember. I'm not convinced we should do this.

**Comment by bohdan-shulha** [comment]
I see, totally valid point. Thanks for explanation.

**Comment by kelunik** [comment]
I wouldn't call this hacky. Variable names that don't conflict are easy to generate, e. g. gg_jte_for_entered_<uuid>. There's no need to track nested loops.

While you can do the same with an if, it creates additional nesting in the template and requires storing the collection in a variable if it's not a simple getter but a computed getter in order to avoid computing the result twice.

**Comment by casid** [comment]
@bohdan-shulha I gave this a shot this morning and it turned out to be not as complicated as I thought. @kelunik's proposed solution worked out quite nicely.

I won't be at my computer this weekend, but I'll try to teach the IntelliJ plugin the new syntax next week!

**Comment by casid** [comment]
I adjusted the IntelliJ plugin. My test code doesn't make a lot of sense, but it seems to work very well out of the box :-).

![for-else](https://github.com/casid/jte/assets/4077354/55c62a55-3511-4dc9-9a81-351758911578)

**Comment by bohdan-shulha** [comment]
Wow, thank you!

Looks awesome! :)

**Comment by casid** [comment]
@bohdan-shulha I released jte 3 today, feel free to have look :-)
