### ISSUE TITLE
Weird Ktor ClassLoader in debug mode

### ISSUE THREAD

**Issue by MoMMde** [casid/jte#241]
Hello, i came across #35 introducing specified ClassLoaders. Now, when i try to use Ktor with the JTE Plugin, it works fine as long as i keep  Ktors `developmentMode` false. 
When i turn this `developmentMode` on, and try to pass a Model into the Template, i get a `ClassCastException`

```
Caused by: java.lang.ClassCastException: class xyz.mommde.wisdom.models.Account cannot be cast to class xyz.mommde.wisdom.models.Account (xyz.mommde.wisdom.models.Account is in unnamed module of loader io.ktor.server.engine.OverridingClassLoader$ChildURLClassLoader @22757faa; xyz.mommde.wisdom.models.Account is in unnamed module of loader 'app')
```

And now the scuffed part.
When I call `io.ktor.server.engine.ApplicationEngineEnvironmentBuilder#getClassLoader` (aka. Ktors ClassLoader) in the Plugin Configuration Scope, it works. 

**Works**
![image](https://github.com/casid/jte/assets/80107781/12625c1c-7957-4a7a-b63e-665a9e5230fe)

**Doesn't Work**
![image](https://github.com/casid/jte/assets/80107781/64a6479f-b05f-4bd3-b6cb-3a8b4995ac77)

I dont know you need this, but i will provide them anyway.
Gradle: 8.1.1
Kotlin: 1.8.22
Ktor Version: 2.3.1

**Comment by MoMMde** [comment]
As i can live with calling `classLoader` for (no) reason, this issue is also there to help people who face the same issue

**Comment by casid** [comment]
Thanks for reporting this. I wonder if your fix can be added to the ktor jte plugin?

**Comment by 2x2xplz** [comment]
Hi, @MoMMde, am I applying your suggestion correctly? Because I continue to have issues in ktor dev mode.

<img width="832" alt="image" src="https://github.com/user-attachments/assets/c6397000-118b-482e-b77b-5238ba28dbf1">

(and `ktorTemplateEngine` is very basic)
<img width="924" alt="image" src="https://github.com/user-attachments/assets/cc061093-707a-4e44-9091-e1040f70819d">

I have turned off ktor development mode (and removed the classLoader, because it isn't resolving the issue), but it would be nice to keep it on. Not sure if it's simply not working, or if I am referencing the wrong classLoader or something.

Thanks for the help.

**Comment by MoMMde** [comment]
Well as far as i can see, you are creating a new instance of `ApplicationEngineEnvironmentBuilder`. In my example i'm using the `getClassLoader` function from the Lambda parameter

**Comment by Kinchkun** [comment]
FYI. The solution in this thread didn't work for me but the following did work:

```kotlin
install(Jte) {
        val classLoader = Thread.currentThread().contextClassLoader
        val resolver = ResourceCodeResolver("templates", classLoader)
        templateEngine = TemplateEngine.create(resolver, Paths.get("kte"), ContentType.Html, classLoader)
    }
```

Since ktor mode sets this classloader: https://github.com/ktorio/ktor/blob/main/ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/EmbeddedServerJvm.kt#L139

**Comment by 2x2xplz** [comment]
@Kinchkun thank you for posting your code. Is jte's built-in hot reloading still working? In my tryouts, using your solution, I lose the jte hot reloading, even when ktor development mode is still turned off.

**Comment by 2x2xplz** [comment]
@MoMMde Sorry to bring this up again, can you post the full code you use to initialize jte and all the associated components (especially the class loader). My attempt above, as you pointed out, was creating a new classLoader, however I do not appear to have access to a native or previously-existing one, or to a getClassLoader() function, probably because I can't seem to get your suggested syntax correct. I'm also trying to use application.conf rather than EmbeddedServer. I'm also curious if your solution has jte's built-in hot reloading and ktor's development mode's reloading both working. Again, sorry to bug you - but thanks.

@casid I love jte and have successfully built numerous projects with it (and recommend it often) -- but I have never NOT experienced this error when using the ktor/jte plugin, and that's with jte v.1, 2, and 3 and ktor v. 1, 2, 3. As such, I've never been able to turn on ktor's development mode -- not a dealbreaker but annoying. I have to imagine my experience is not unique and perhaps some documentation on how to avoid it might improve overall adoption of this fantastic library. Thank you.

**Comment by yamin8000** [comment]
> FYI. The solution in this thread didn't work for me but the following did work:
> 
> install(Jte) {
>         val classLoader = Thread.currentThread().contextClassLoader
>         val resolver = ResourceCodeResolver("templates", classLoader)
>         templateEngine = TemplateEngine.create(resolver, Paths.get("kte"), ContentType.Html, classLoader)
>     }
> 
> Since ktor mode sets this classloader: https://github.com/ktorio/ktor/blob/main/ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/EmbeddedServerJvm.kt#L139

This should be added to jte's documentation for Kotlin and Ktor.
