### ISSUE TITLE
Can't have unclosed tags after upgrading to 3.0.1

### ISSUE THREAD

**Issue by IvanPizhenko** [casid/jte#250]
I have few separate KTE files used as components in other KTE pages.
One of them is pair of "cardBegin.kte" and "cardEnd.kte", which, omitting details, contain something like this:
```html
<div ...>
  <div ...>
    <div ...>
```
and
```
    </div>
  </div>
</div>
```
Now I'm getting error like this from JTE plugin:
```
Execution failed for task ':my-project:generateJte'.
> There was a failure while executing work items
   > A failure occurred while executing gg.jte.gradle.GenerateJteWorker
      > Failed to compile tag/row/card/cardBegin.kte, error at line 10: Unclosed tag <div>.
```

**Comment by IvanPizhenko** [comment]
I'd like to have an option which turns off such behavior and lets me use my exisiting codebase instead of spending lots of time for refactoring.

**Comment by casid** [comment]
Hey @IvanPizhenko,

I can understand your frustration with this change. This feature was part of the major version bump from jte 2 to jte 3. I haven't anticipated that it would have such an effect, and missed to notice it in the release notes, it was just mentioned in the issue: https://github.com/casid/jte/issues/194. I'll add this to the release notes, with a hint how to migrate. I'll also add a hint to the compile error, pointing to `gg.jte.Content`.

However, we did this change because we believe this will result in much cleaner templates, that will be better to maintain in the long run. Not only will this read better in IntelliJ, also users of such templates won't be able to forget a closing template anymore.

For instance your example could be written as `card.kte`:

```html
@import gg.jte.Content

@param Content content

<div ...>
  <div ...>
    <div ...>
       ${content}
    </div>
  </div>
</div>
```

If you don't want to migrate right away, it is perfectly fine to stay on jte 2 until you are ready for the change. And maybe give `gg.jte.Content` a try for new templates. I'm very sure you're gonna like it as much as we do!

**Comment by casid** [comment]
I've updated the jte 3 release notes, that they contain this under breaking changes: https://github.com/casid/jte/releases/tag/3.0.0

**Comment by IvanPizhenko** [comment]
Thank you for updating RN. But still, I'd say it should be rather up to end-user to decide what to do. If someone wants to continue this "open something/close something pair", it is better to provide them such possibility, even at cost of potential possibility of HTML w/o closed tags, because those users think that still better for them. So still, I'd like to have a programmatic option that turns this check off.

**Comment by IvanPizhenko** [comment]
Also, even if your "new coding style" is really good, and someone decided to migrate the code, but what if there are lot of pages to modify and they just can't afford rewriting all of them at once, but it be would rather better to do it step by step? Did you think about such development scenario? That's one more reason why an option that disables this check will be very useful.

**Comment by casid** [comment]
The "new coding style" has been available since the first versions of jte.

The step by step migration can be done by sticking to jte 2 and migrating templates step by step. Once all templates are adjusted, the version can be bumped to jte 3.

I'm still not convinced an option is a good idea as it introduces more complexity and needs to be carried through all future versions. If we'd decide to remove the option in jte 4, for users with this option activated, there would be even more code to migrate than there is right now.

**Comment by casid** [comment]
@spinscale I'm mentioning you here, because you ran into the same problem. Any thoughts about this?

**Comment by spinscale** [comment]
I'm on the `If a user has a bad time, it's a bug` side of things (from Jordan, the creator of [logstash](https://github.com/elastic/logstash)) here - and obviously cause I ran into it myself 😀

After staring at it the last days the '@``' notation is still less readable to me.

I do think, outputting valid HTML is super powerful though. Maybe that could be done as a last step after concatenation, or when precompiling templates instead? Keep in mind: Those are just weird suggestions from someone who does not know JTE internals, feel free to ignore me entirely.

**Comment by kelunik** [comment]
> I'm on the If a user has a bad time, it's a bug side of things

We have this now because the behavior was different before. Given the exception message, I don't think new users will have a problem here.

Libraries should make doing the correct thing easy and make making mistakes hard.

Unclosed tags always mean you'll have to touch two files and know which one is the second file. This makes mistakes easy.

**Comment by casid** [comment]
Thanks for sharing your thoughts on this @spinscale.

> Maybe that could be done as a last step after concatenation

This would mean throwing a runtime exception, which will annoy users in production instead of compile time. It would also slow down template execution. Valid HTML templates would get a speed penalty for no good reason.

> when precompiling templates instead?

That's kind of what this feature is trying to accomplish. Since users can call one of the two templates on their own (e.g. `templateEngine.render("open-tags.jte")`) it must fail this way at compile time.

**Comment by IvanPizhenko** [comment]
I would support opinion, that "@" notation less readable.
But I am totally ok with dealing with tags in multiple files, in my case it all already written and doesn't change, so I don't have this problem at all.

**Comment by casid** [comment]
Out of curiosity, are you working with the jte IntelliJ plugin? I'm quite happy with content block layouts.

![content-block](https://github.com/casid/jte/assets/4077354/f058fff6-40c9-4fa9-8baa-8f06dab9d12f)

Without the plugin, I agree it to be less readable.

I'd still feel quite nervous about this alternative though ;-)

```html
@template.layout.beginPage(page = page)
...
@template.layout.endPage(page = page)
```

**Comment by IvanPizhenko** [comment]
Yes, I'm working with IntelliJ plugin.

**Comment by spinscale** [comment]
Using the plugin as well, which makes working with JTE a breeze.

**Comment by asm0dey** [comment]
I have the same issue but generate XML, which should have an unclosed `<?xml>` tag. Is there a way to fix this?

**Comment by chkl** [comment]
@asm0dey : As a workaround for the unclosed tag, you could try to render the the `<?xml>` at runtime instead of compile time. For example: 

```java
public static class XmlUtil {
   public Content xmlHeader() {
    return output -> output.writeUnsafeContent("<?xml>");
  }
}
```

And then include this in your jte layout:
```jte
${XmlUtil.xmlHeader()}
<document>
<!-- ... -->
</document>
```
Feels more like a hack though.

**Comment by IvanPizhenko** [comment]
> The "new coding style" has been available since the first versions of jte.
> 
> The step by step migration can be done by sticking to jte 2 and migrating templates step by step. Once all templates are adjusted, the version can be bumped to jte 3.
> 
> I'm still not convinced an option is a good idea as it introduces more complexity and needs to be carried through all future versions. If we'd decide to remove the option in jte 4, for users with this option activated, there would be even more code to migrate than there is right now.

You just don't need to remove it. :)

**Comment by casid** [comment]
@asm0dey oh wow, I did not expect that jte would be used to generate XML :-)

I've adjusted the code, so that declaration tags are not expected to be closed.

**Comment by stella6767** [comment]
i got same probleam. after upgrade jte 3. this .jte file dont work. i have to do close form tag.. with duplicated html content
is there a good solution?

@if(idAncestor != 0)
<form class="bg-white rounded-lg border p-2 mx-auto "
      id="comment-form"
      hx-post="/comment"
      hx-target="#comment-card-${idAncestor}"
      hx-swap="beforeend"
>
@else

<form class="bg-white rounded-lg border p-2 mx-auto "
      id="comment-form"
     ...
>

@endif


        <div class="px-3 mb-2 mt-2">
            <textarea placeholder="comment" disabled="${!isLogin}"
                      name="content" form="comment-form"
                      class="w-full bg-gray-100 rounded border border-gray-400 leading-normal resize-none h-20 py-2 px-3 font-medium placeholder-gray-700 focus:outline-none focus:bg-white"></textarea>
        </div>

....

</form>

**Comment by casid** [comment]
@stella6767 you can do it like this. This way IntelliJ should also not complain about an unclosed form tag.

```html
!{var content = @`
   <div class="px-3 mb-2 mt-2">
            <textarea placeholder="comment" disabled="${!isLogin}"
                      name="content" form="comment-form"
                      class="w-full bg-gray-100 rounded border border-gray-400 leading-normal resize-none h-20 py-2 px-3 font-medium placeholder-gray-700 focus:outline-none focus:bg-white"></textarea>
        </div>
`;}

@if(idAncestor != 0)
<form class="bg-white rounded-lg border p-2 mx-auto "
      id="comment-form"
      hx-post="/comment"
      hx-target="#comment-card-${idAncestor}"
      hx-swap="beforeend"
>
   ${content}
</form>
@else

<form class="bg-white rounded-lg border p-2 mx-auto "
      id="comment-form"
     ...
>
   ${content}
</form>

@endif

```

**Comment by stella6767** [comment]
> @stella6767 you can do it like this. This way IntelliJ should also not complain about an unclosed form tag.
> 
> ```
> !{var content = @`
>    <div class="px-3 mb-2 mt-2">
>             <textarea placeholder="comment" disabled="${!isLogin}"
>                       name="content" form="comment-form"
>                       class="w-full bg-gray-100 rounded border border-gray-400 leading-normal resize-none h-20 py-2 px-3 font-medium placeholder-gray-700 focus:outline-none focus:bg-white"></textarea>
>         </div>
> `;}
> 
> @if(idAncestor != 0)
> <form class="bg-white rounded-lg border p-2 mx-auto "
>       id="comment-form"
>       hx-post="/comment"
>       hx-target="#comment-card-${idAncestor}"
>       hx-swap="beforeend"
> >
>    ${content}
> </form>
> @else
> 
> <form class="bg-white rounded-lg border p-2 mx-auto "
>       id="comment-form"
>      ...
> >
>    ${content}
> </form>
> 
> @endif
> ```

Your solution makes me happy.

**Comment by casid** [comment]
@asm0dey just wanted to let you know that your XML issue should be fixed in jte 3.0.2.

**Comment by asm0dey** [comment]
@casid thank you, but I'm afraid, I've already rewritten all 5 of my xmls to https://github.com/redundent/kotlin-xml-builder, sorry :(

**Comment by IvanPizhenko** [comment]
That's what I was talking about when I said: you must be backward compatible to have people using your library.

**Comment by casid** [comment]
To be fair I think kotlin-xml-builder is the much better tool for creating XML than jte is, so that's not a bad outcome at all :-)

**Comment by asm0dey** [comment]
Well, I'm not sure because it requires writing a lot of code instead of just markup. Also, I'm not sure about performance (but it's not important in my case)
