### ISSUE TITLE
`No script runtime error` when rendering `kte` templates on latest IntelliJ 

### ISSUE THREAD

**Issue by sureshg** [casid/jte#260]
I am using JTE as part of a Gradle pre-compiled script plugin to generate buildconfig  and IntelliJ IDE is started showing `No script runtime was found in the classpath` error . Everything was fine recently and i am not sure since when it started having this IDE issue. Any idea what's happening here? By the way, gradle build is working fine as expected, the issue is only on IDE.

### Env

```
IntelliJ IDEA 2023.2.1 Preview (Ultimate Edition)
         Build #IU-232.9559.10, built on August 9, 2023
         org.jusecase.jte-intellij (2.1.0)
         Kotlin: 232-1.9.0-IJ9559.10
Jte.        :  3.0.2
Gradle      :  8.3-rc-4
Kotlin.     :  1.9.0
````

### JTE Config

```kotlin
// jte  = "3.0.2"
plugins {
  `kotlin-dsl`
  alias(libs.plugins.jte)
  ...
}

jte {
  contentType = gg.jte.ContentType.Plain
  sourceDirectory = sourceSets.main.map { it.resources.srcDirs.first().toPath() }
  generate()
}

dependencies {
  implementation(libs.jte.runtime)
}
```
### IDE Error

```
No script runtime was found in the classpath: class 'kotlin.script.templates.standard.ScriptTemplateWithArgs' not found. Please add kotlin-script-runtime.jar to the module dependencies.
```
<img width="1060" alt="Screenshot 2023-08-15 at 5 47 46 AM" src="https://github.com/casid/jte/assets/356994/e5728bde-eefc-4345-b135-7a5dcf80c180">

**Comment by casid** [comment]
Hmm, that's weird. So I assume it started with the IntelliJ upgrade and worked normally before?

I had a quick look at the plugin and found this:
https://github.com/casid/jte-intellij/blob/6193b3870016f42155de503660a2985d761df8ac/src/main/java/org/jusecase/jte/intellij/language/KteKotlinLanguageInjector.java#L293

We explicitly request Kotlin as language here, but there's an overload to `startInjtecting` that takes a file extension as second parameter. I'll give it a try if this change helps to force Kotlin instead of Kotlin Script:

`registrar.startInjecting(KotlinLanguage.INSTANCE, "kt");`

Unfortunately I won't be able to test it until somewhere next week.

If you need a fix for it sooner, you could try to check out the plugin, apply the fix, build a local version of the plugin and test with it.

**Comment by sureshg** [comment]
> So I assume it started with the IntelliJ upgrade and worked normally before?

I think so.

>registrar.startInjecting(KotlinLanguage.INSTANCE, "kt");

Yup, that did the trick. I built and updated the plugin and it seems ok now.
<img width="790" alt="Screenshot 2023-08-16 at 7 12 09 PM" src="https://github.com/casid/jte/assets/356994/c1e03691-8f97-44cb-bf02-ab520aaf9b1a">

**Comment by casid** [comment]
Aww, thanks for testing and the confirmation!

I've applied the fix and published a new plugin version. Will probably take 1-2 days to go through JetBrains Review.
