### ISSUE TITLE
not work in Spring-Boot

### ISSUE THREAD

**Issue by shinestmt** [casid/jte#261]
without Physical File

```
class MemoryCodeResolver implements CodeResolver { 
    // memoryCodeResolver.put(name, sqlTemplate)
    // memoryCodeResolver.get(name)
}

```

All in memory
```
String sql = """
            SELECT id,name,age,grade FROM demo_user 
            where age = ${user.getAge()}
            @if(user.getGrade() != null)
              grade = ${user.getGrade()}
            @endif
            """
engine = TemplateEngine.create(memoryCodeResolver, ContentType.Plain)
memoryCodeResolver.put("selectList", sql)


StringOutput output = new StringOutput()
engine.render("selectList", parameters, output)
```

using Spring-Boot 
[ IDEA debugging ]  --> OK

but
```
# spring boot project
mvn package 

java -jar target/demo.jar

# error
```

Does it support Memory Compile?
like this: 
```
String javaSource = "public class .........."    // generated java code
Class clazz = compiler.compile("selectList", javaSource)   // compile to Class, not xxx.class File
clazz.newInstance()
```

https://github.com/raulgomis/dynamic-java-compiler/tree/master

**Comment by casid** [comment]
Hey, Spring Boot uses its own classloader, so you need to add the classloader to the call where you create the template engine.

`TemplateEngine templateEngine = TemplateEngine.create(codeResolver, Paths.get("jte-classes"), ContentType.Html, getClass().getClassLoader());`

Also, please, for your own sanity and for the security of your database, don't use a template engine to generate SQL queries.

**Comment by apatrida** [comment]
@casid 

> Also, please, for your own sanity and for the security of your database, don't use a template engine to generate SQL queries.

There are use cases such as BI systems (i.e. superset), data engineering tools (i.e. SQLMesh) that all do need to use SQL templates and control them by a well designed templating system including encoding parameters into them.  In fact almost ALL of these systems do this, ALL.  You shouldn't outlaw it just because some people want to use it instead of ORM's for CRUD.

instead,  it would be impossible for anyone to use JTE for this if you have no way to encode variables for the specific purpose into the template (i.e. plugable encoder).  Or to turn off any encoding and let the source do it as needed (rougher).  

I remember looking at JTE over a year ago for this and found some problem, but cannot remember if that was hard coded encoders or no way to turn them off, etc.

**Comment by apatrida** [comment]
ok, if you WERE to do SQL: (via AI)

Are encoders pluggable?

Partially. There are two extension points:

• HtmlTemplateOutput interface (jte-runtime/.../html/HtmlTemplateOutput.java) — If you pass a TemplateOutput that already implements HtmlTemplateOutput, the engine skips wrapping it with OwaspHtmlTemplateOutput. So you can provide your own encoding implementation by implementing HtmlTemplateOutput directly.

• HtmlPolicy interface (jte-runtime/.../html/HtmlPolicy.java) — This handles compile-time validation of HTML structure (e.g., preventing unquoted attributes, inline event handlers). Fully pluggable via TemplateEngine.setHtmlPolicy().

However, there's no generic ContentEncoder plugin interface. The encoding strategy is hard-tied to the ContentType enum — it's either "no encoding" (Plain) or "OWASP HTML encoding" (Html).

Can encoding be turned off?

Yes, a few ways:
• Globally: Use ContentType.Plain when creating the engine — no encoding is applied at all.
• writeUnsafeContent() - Called for unsafe markup $unsafe{variable} - NO ESCAPING (raw passthrough)
• Per-expression: Use $unsafe{expression} in templates — this calls writeUnsafeContent() which passes through raw content with zero encoding.

Can new encoders be added (i.e. SQL)?

No. Not without modifying JTE itself. Here's why:
• ContentType is a closed enum with only Plain and Html. You can't add Sql without changing the source.
• The checkOutput() logic in TemplateEngine only knows about Html — it has no mechanism to select a different encoder based on a new content type.
• The code generators (JavaCodeGenerator, KotlinCodeGenerator) emit different code paths for Html vs Plain — HTML gets setContext() calls for tag/attribute tracking, which wouldn't apply to SQL.

To add SQL encoding, you would need to:

1. Add Sql to the ContentType enum - Context-aware escaping (lines 309-325):
2. Create a SqlTemplateOutput (analogous to OwaspHtmlTemplateOutput) that implements the appropriate escaping (parameterized query encoding, identifier quoting, etc.)
	• For HTML templates, the generator calls setContext(tagName, attributeName) before outputting variables
	• This allows OwaspHtmlTemplateOutput to choose the right escape method
3. Update TemplateEngine.checkOutput() to wrap output for the new content type
4. Possibly update the code generators if SQL needs its own context tracking (like HTML tracks tags/attributes)

Policy interfaces & implementations:

Workaround without modifying JTE: Use ContentType.Plain and implement a custom TemplateOutput that does SQL escaping in writeUserContent(). You lose the automatic context-aware escaping, but you can still intercept all user content at the output level. The writeUserContent(String) default method on TemplateOutput is overridable.

**Comment by apatrida** [comment]
So if you wanted to context sensitive encode:

* fully qualified table/view/object names
* a function name
* literal in SQL (i.e. some things only accept literals, not bind vars)
* bind variables (leave them as-is `:whatever` and use JOOQ/Ibatis param binder to bind them)

you wouldn't have enough information to do so without having the controller pass in where you are in the AST.

**Comment by apatrida** [comment]
You can make it work setting to `plain` and then adding helpers that return `TemplateOutput`

A bad example, but whatever:

```
SELECT ${asColumns(columns, "foo")} FROM ${asTable(schemaVar, tableVar)} AS foo WHERE ${asLiteral(nameVar)} = ${asBind(valueVar)}
```

```
public static Content asTable(String schema, String table) {
    return output -> {
        // Validate/encode each segment as a SQL identifier
        output.writeContent(quoteIdentifier(schema) + "." + quoteIdentifier(table));
    };
}

public static Content asLiteral(String value) {
    return output -> {
         ...
    };
}

public static Content asBind(String paramName) {
    return output -> {
        ...
    };
}

private static String quoteIdentifier(String identifier) {
    ...
}
```

You would want to never allow raw strings actually so would want to protect that.

```
public class SqlTemplateOutput implements TemplateOutput {
    private final TemplateOutput delegate;

    public void writeContent(String value) {
        delegate.writeContent(value); // trusted, from Content helpers
    }

    public void writeUserContent(String value) {
        throw new IllegalStateException(
            "Raw string interpolation not allowed in SQL templates. " +
            "Use asTable(), asLiteral(), or asBind().");
    }

    public void writeUserContent(Content content) {
        content.writeTo(this); // Content controls its own encoding
    }
    // ... delegate other writeUserContent overloads similarly
}
```

Then pass this as your output when rendering, and any bare ${stringVar} blows up at render time, forcing the author to be explicit about context. That gets you closer to the HTML model's safety guarantee, albeit at runtime rather than compile time.

```
// --- Setup ---

// Use Plain since we're handling encoding ourselves
TemplateEngine engine = TemplateEngine.create(
    codeResolver, ContentType.Plain
);

// --- Render ---

SqlTemplateOutput sqlOutput = new SqlTemplateOutput(new StringOutput());
engine.render("queries/find-users.jte", model, sqlOutput);

String sql = sqlOutput.toString();
```

if someone tried:

```
WHERE name = ${nameFilter}

> error
IllegalStateException: Raw string interpolation not allowed in SQL templates.
Use asTable(), asLiteral(), asBind(), or asIdentifier().
```


fuller SqlTemplateOutput:

```
public class SqlTemplateOutput implements TemplateOutput {
    private final TemplateOutput delegate;

    public SqlTemplateOutput(TemplateOutput delegate) {
        this.delegate = delegate;
    }

    @Override
    public void writeContent(String value) {
        delegate.writeContent(value); // Static template text, trusted
    }

    @Override
    public void writeContent(String value, int beginIndex, int endIndex) {
        delegate.writeContent(value, beginIndex, endIndex);
    }

    @Override
    public void writeUserContent(String value) {
        throw new IllegalStateException(
            "Raw string interpolation not allowed in SQL templates. " +
            "Use asTable(), asLiteral(), asBind(), or asIdentifier()."
        );
    }

    @Override
    public void writeUserContent(Content content) {
        if (content != null) {
            content.writeTo(this); // Content helper does its own encoding
        }
    }

    @Override
    public void writeUserContent(int value) {
        // Numeric types are safe to pass through
        delegate.writeContent(String.valueOf(value));
    }

    @Override
    public void writeUserContent(long value) {
        delegate.writeContent(String.valueOf(value));
    }

    @Override
    public void writeUserContent(boolean value) {
        delegate.writeContent(String.valueOf(value));
    }

    // ... same for byte, short, float, double

    @Override
    public String toString() {
        return delegate.toString();
    }
}
```

you could generalize this NOT for SQL but for anything that you want "pre-approved content only" instead of `plain`

**Comment by edward3h** [comment]
You can use JTE however you like. Templating SQL is not an intended use case though.

If you're working with SQL, there are _many, many_ Java libraries that are better suited, without being ORMs. e.g.

* My own [Kiwiproc](https://edward3h.github.io/kiwiproc/)
* [jOOQ](https://www.jooq.org/)
* [Spring Data JDBC](https://spring.io/projects/spring-data-jdbc)
* [JDBI](https://jdbi.org/#_introduction_to_jdbi_3)

**Comment by apatrida** [comment]
a lot of things that do not do conditional logic in SQL that is more along the lines of SQLMesh than ORM.  The only part of value from JOOQ or JDBI would be the named parameter substitution.  It is a templating problem, and this is a templating library.  One that has an opinion against templating SQL even for use cases that typically template SQL.

**Comment by casid** [comment]
Thanks for clarifying. Our strong stance here is intentional: jte is a templating engine, but that does not mean we want to support every possible templating use case.

SQL has its own safety and correctness requirements: parameter binding, escaping, dialect differences, query validation, and injection risks. Once jte officially supports SQL templates, users will reasonably expect us to handle or guide them through those concerns. That is not a direction we want to take the project.

Even when the use case is “just named parameters” or “some conditional query fragments”, it quickly becomes database-specific query generation. That space is already served much better by libraries such as jOOQ, JDBI, SQL builders, ORMs, or tools like SQLMesh, depending on the problem. Those libraries understand SQL as SQL; jte does not and should not.

We do not want jte to encourage or officially support SQL templating, because it creates a maintenance and safety burden while offering little value over dedicated database tooling.

Keeping jte focused also helps us maintain its quality. We would rather be opinionated here than add a feature we do not believe is a good fit and then have to support it long-term.
