### ISSUE TITLE
Support JSON ContentType

### ISSUE THREAD

**Issue by spinscale** [casid/jte#3]
I'd like to use this template language to fill in some large JSON. Do you think it makes sense to have a `ContentType.Json`, that escapes all JSON values like done [here in JsonValue.escape()](https://github.com/fangyidong/json-simple/blob/master/src/main/java/org/json/simple/JSONValue.java#L270-L314)?

**Comment by casid** [comment]
Is the JSON you're going to create so big, that JSON libraries can't do the job? I'd definitely recommend to use a JSON lib instead of a template engine for this job.

Besides escaping, a `ContentType.Json` would have to somehow validate the structure of the JSON as well. Kind of like `ContentType.Html` validates the HTML at compile time.

Maybe you could give try `ContentType.Plain` and escape stuff manually, just to see if jte is fast enough / the tool you want  for your usecase?

**Comment by spinscale** [comment]
I basically have templated Elasticsearch queries that can be several kb in size, where the search term that the user entered is the only variable input at a couple of places within the JSON - therefore I will not build the JSON everytime, but wanted to defer to jte. I'm currently falling back to the plain text solution with manual escaping. I'm good doing, just figured it might be an interesting extension. Feel free to close, if that is good enough from your perspective!

**Comment by casid** [comment]
Interesting! And thanks for sharing. Pretty cool how you're using jte for elastic search queries. Never thought about that before 👍 

I'm going to close it for now, since I believe creating JSON won't be the primary use case of jte. And the lib is already bigger than I'd like it to ;-) And I guess if one is building JSON or XML with a template engine knows what he's doing.

**Comment by spinscale** [comment]
Just for the internet archive and google. I solved this with a special output, that escapes user content like this

```java
    private static final class JsonStringOutput extends StringOutput {
        @Override
        public void writeUserContent(String value) {
            super.writeUserContent(escape(value));
        }
    }

    String render(final String templateName, final Map<String, Object> params) {
        try (StringOutput output = new JsonStringOutput()) {
            templateEngine.render(templateName + ".jte", params, output);
            return output.toString();
        }
    }

    public String string escape(String input) {
       ...
    }
```

I used the escape logic from minimal-json at https://github.com/ralfstx/minimal-json/blob/master/com.eclipsesource.json/src/main/java/com/eclipsesource/json/JsonWriter.java

**Comment by kelunik** [comment]
@spinscale Seems like it's easy enough to solve without specialized support. Instead of only escaping strings, something like fastjson's `JSON.toJSONString()` converting any object might be good.

It might be a good idea to decouple some things, so full support can be implemented by plug-ins.
