### ISSUE TITLE
Selective Escaping in HTML mode

### ISSUE THREAD

**Issue by sirinath** [casid/jte#33]
In order to limit the performance penalty, one pays in `html` mode, it is possible to have finer control over that is escaped. Certain parameters can be specified as safe or raw which will bypass escaping.

**Comment by casid** [comment]
Hey @sirinath.

You can use `$unsafe{}` instead of `${}` to do this. However, I'd advice against it, since it shouldn't make a huge difference in performance (as long as those texts are not huge, see below), and there's always the chance to shoot yourself in the foot with it :-)

In case you have large text parts you want to render, you could consider wrapping them in `gg.jte.Content` and render them normally with `${}`. We use this quite a bit for [localization keys](https://github.com/casid/jte/blob/master/jte-runtime/src/main/java/gg/jte/support/LocalizationSupport.java), which might include HTML attributes that shouldn't be escaped but parameters should be.

**Comment by casid** [comment]
@sirinath did this answer your question? Can we close this?

**Comment by casid** [comment]
Thanks!
