### ISSUE TITLE
JSP style on demand background compilation.

### ISSUE THREAD

**Issue by hurelhuyag** [casid/jte#37]
Hi, 
First thank you this great project. 
Here is my question. Is there any plan for JSP style on demand background compilation support?
Sometimes changing template file without restarting is great. Front-End appearance requires lot of small changes frequently. Typo, label text, text color etc.

**Comment by tstsogoo** [comment]
![image](https://user-images.githubusercontent.com/5563392/103084847-f943db80-461a-11eb-9f99-d2801c361fcf.png)

**Comment by casid** [comment]
@hurelhuyag thanks for the heads up!

@tstsogoo is right, jte already supports hot reload during development, when using a `DirectoryCodeResolver`.

```java
var codeResolver = new DirectoryCodeResolver(Path.of("jte")); // This is the directory where your .jte files are located.
var templateEngine = TemplateEngine.create(codeResolver, ContentType.Html);
```

Maybe you used a `ResourceCodeResolver`? That one does not support hot reload.

**Comment by hurelhuyag** [comment]
If hot reload is like JSP does why it is not recommended in production environment? I'm expecting production grade hot reloading feature.

**Comment by casid** [comment]
Obviously, you can use jte in production the same way as during development.

There are few reasons I would not recommend it:

- Performance: Hot reloading does an additional check on the file system, which is almost always unneccessary on a production system
- Security: Hot reloading on production requires a JDK to recompile templates. If you are able to change templates on production, you really have to secure this. If something goes wrong, you immediately have a remote code execution vulnerability

That being said, since version 1.5.0 there is a way for hot reload on production, without paying the performance penalty. [This unit test](https://github.com/casid/jte/blob/1.5.0/jte/src/test/java/gg/jte/TemplateEngine_PrecompiledReloadableTest.java) illustrates how you'd do that. However, the security concern is still valid, so please be careful.

**Comment by hurelhuyag** [comment]
Thanks. I got it.
