### ISSUE TITLE
Failing to compile template in a kubernetes pod

### ISSUE THREAD

**Issue by gitdunamis** [casid/jte#40]
Hi,

I'm using jte as a template engine to get a string output via `StringOutput`. The content type chosen for `gg.jte.TemplateEngine` is html. Everything is fine when I run the app locally with adopt-hotspot jdk 15, but jte is failing with `TemplateException` when I run the app in a kubernetes pod. The error is something like:  package gg.jte.html  does not exist. Here is the stack trace:

`
 gg.jte.TemplateException: Failed to compile template, error at success_debit_customer.jte:6
/jte-classes/gg/jte/generated/Jtesuccess_debit_customerGenerated.java:5: error: package gg.jte.html does not exist
public static void render(gg.jte.html.HtmlTemplateOutput jteOutput, gg.jte.html.HtmlInterceptor jteHtmlInterceptor, Double amount) {​​​​​​​​
^
/jte-classes/gg/jte/generated/Jtesuccess_debit_customerGenerated.java:5: error: package gg.jte.html does not exist
public static void render(gg.jte.html.HtmlTemplateOutput jteOutput, gg.jte.html.HtmlInterceptor jteHtmlInterceptor, Double amount) {​​​​​​​​
^
/jte-classes/gg/jte/generated/Jtesuccess_debit_customerGenerated.java:32: error: package gg.jte.html does not exist
public static void renderMap(gg.jte.html.HtmlTemplateOutput jteOutput, gg.jte.html.HtmlInterceptor jteHtmlInterceptor, java.util.Map<String, Object>
params) {​​​​​​​​
^
/jte-classes/gg/jte/generated/Jtesuccess_debit_customerGenerated.java:32: error: package gg.jte.html does not exist
public static void renderMap(gg.jte.html.HtmlTemplateOutput jteOutput, gg.jte.html.HtmlInterceptor jteHtmlInterceptor, java.util.Map<String, Object>
params) {​​​​​​​​
^
4 errors
`

So I compared the generated files in `jte-classes/gg/jte/generated` on my local machine to files of the same directory in the pod and I saw that the files generated in the pod do not have any import directive importing the class `gg.jte.html.TemplateOutput` while the ones on my machine had the import directives.

I really don't know how to solve this any help would be appreciated.

Thanks.

**Comment by casid** [comment]
Hi @gitdunamis,

hmm, the generated files us `gg.jte.html.HtmlTemplateOutput`, so the import shouldn't be required. It's very weird that the generated code differs, since that's generated via plain old Java before being passed to the compiler.

I think the problem here is that Java Compiler within the pod does not include the application class path, like OpenJDK, thus the classes cannot be found. It looks very similar to #38 (running WAR on standalone Tomcat).

However, I would recommend to use the ad-hoc compilation only when developing, since jte will check the file system for changes whenever a template is rendered, which causes a small performance hit and usually is only needed during development.

Precompiling all jte templates in your build and initializing a precompiled template engine when running in the pod should work. jte does a lot of compilation checks, it's pretty cool to have them all done on the build step instead of on the live system, too :-)

https://github.com/casid/jte/blob/master/DOCUMENTATION.md#precompiling-templates

Let me know if this helps!

**Comment by gitdunamis** [comment]
@casid 
Thanks, I will try pre-compiling the templates and provide results. Thanks for the response

**Comment by harrison-nc** [comment]
Hi, I am getting the same error while using jte on my local machine in a Quarkus Project.

How is a a java source file generated from a jte template file compiled?
How I can observed how jte creates the classpath used to compile generated java source file?

I thing the classpath is not been set that is why I am getting this error.

Please, is there any proper solution to this issue. Thanks.

**Comment by casid** [comment]
Quarkus is quite tricky, since it basically comes with its own build pipeline.

There was some work on a Quarkus integration last year, that integrates jte into the Quarkus build tooling: https://github.com/renannprado/quarkus-jte-extension/
