### ISSUE TITLE
java.lang.Number support.

### ISSUE THREAD

**Issue by hurelhuyag** [casid/jte#43]
I saw `TemplateOutput` interface. There is `Enum` is only one has specially supported. What do you think about other classes. `Number`, `BigDecimal`, `BigInteger` etc. 

Currently I'm writing template like this
```
@param java.math.BigDecimal monthlyPrice
!{var BIG_DECIMAL_12 = java.math.BigDecimal.valueOf(12);}
<span>${monthlyPrice.toString()}</span>
<span>${monthlyPrice.multiply(BIG_DECIMAL_12).toString()}</span>
```

I think this will be better. What do you think?
```
@param java.math.BigDecimal monthlyPrice
<span>${monthlyPrice}</span>
<span>${monthlyPrice * 12}</span>
```

**Comment by casid** [comment]
Hey @hurelhuyag, `TemplateOutput` is rather dumb by design.

Usually you will want stuff formatted consistently through your application (e.g. HMTL, REST, PDF, whatsoever..).

When this is done by the template engine, it won't be possible to do that and couple the formatting to this particular engine.

Maybe you have already some code that formats money. I'd recommend to expose call that from jte templates. Maybe you can get yearlyPrice through business logic, not calcualate it within the template, too?

Something like:

```html
@import static my.JteContext.*

@param my.Product product

<span>${formatMoney(product.getMonthlyPrice())}</span>
<span>${formatMoney(product.getYearlyPrice())}</span>
```

I usually have some kind of JteContext for that stuff.

```java
import 
public class JteContext {
   public static String formatMoney(MonetaryAmount amount) {
       MonetaryAmountFormat format = MonetaryFormats.getAmountFormat(getLocale());
       return format.format(amount);
   }

   private static Locale getLocale() {
       // Obtain through thread local context
   }
}
```

Benefit is, you can easily reuse your formatting between all parts of the application :-)
