### ISSUE TITLE
Maven generate-sources HtmlPolicy

### ISSUE THREAD

**Issue by Fender123** [casid/jte#46]
Hi, 
is it possible to use a custom HtmlPolicy when using the maven plugin to generate sources during build? 
I want to package the templates with my application (like this: https://github.com/casid/jte/blob/master/DOCUMENTATION.md#using-the-application-class-loader-since-120) 
As I am using Html Attributes without a value for testing (i.e. `<div data-test-important-content>`) I have to use a custom policy. Unfortunately my build is breaking because of the failed policy:

```
Failed to execute goal gg.jte:jte-maven-plugin:1.5.0:generate (default) on project service-frontend: 
Execution default of goal gg.jte:jte-maven-plugin:1.5.0:generate failed: 
Failed to compile tag/shop/communication.jte, error at line 1: Unquoted HTML attribute values are not allowed: data-test-shop-communication
```

**Comment by casid** [comment]
@Fender123 oh, I think that parameter is missing for that build variant - I will have a look!

I also feel that I should fix the default policy. `<div data-test-important-content>` should not be forbidden.

**Comment by Fender123** [comment]
maybe the checks should not be that strict for `data-*` attributes.

**Comment by kelunik** [comment]
@Fender123 Unquoted attributes without value should be allowed for all attributes, so e.g. `<input disabled>` should be allowed, too.

The feature is intended to make the automatic attribute escaping less complex by not having to support various escaping mechanism based on quoting. If attributes do not contain variables, it's probably OK to allow those, too, so e.g. `<input value=foo>`, but AFAIK most people default to quoting always.

**Comment by casid** [comment]
@Fender123 I fixed the policy in https://github.com/casid/jte/commit/7a8dcad2df594b2e2ceeb63f0a6768dfb095fa9e.

Adding HtmlPolicy support to the generator maven plugin is not that easy, because it is executed in the `GENERATE_SOURCES` build phase, where the compiled classes are not available yet. It may be possible to temporarily compile them ad hoc temporarily, but that will make the build pretty complicated.

**Comment by Fender123** [comment]
Thank you. Looks good

**Comment by casid** [comment]
@Fender123 I looked a bit further into providing the HtmlPolicy to the GeneratorMojo and it really would be a mess ^^.

I updated the documentation to better explain how the GeneratorMojo works and its current limitations: https://github.com/casid/jte/commit/7506332f78eee821210ab6cb960c278753b25dd5

I use the CompileMojo for all my jte projects, because of hot-reload problems with the GeneratorMojo. I'm curious if you experienced those as well in your setup?

**Comment by Fender123** [comment]
ok, thanks for the clarification. 

Yes I experienced same strange hot reloading behavior, but not always...

Maybe I should have a look into CompilerMojo as well.

**Comment by casid** [comment]
@Fender123 this morning publishing to maven central worked again. 1.5.1 is live containing this fix 👍
