### ISSUE TITLE
Is there any plan to port the IntelliJ plugin to Visual Studio Code?

### ISSUE THREAD

**Issue by maj2c** [casid/jte#54]
Hi,

First of all thank you for the great work on this template engine, looks very promissing and I want to use in a new project.
I wonder if there is any plan to have a support extension for Visual Studio Code just like there is for IntelliJ Idea.

I would like to help towards the extention but not sure where to start.

Best regards,
maj2c

**Comment by casid** [comment]
Thanks for the heads up!

There are no plans to write a VSCode plugin on my side. I'm a heavy IntelliJ user, so that plugin is enough for my needs.

The IntelliJ plugin is on GitHub and may be a starting point for a VSCode plugin: https://github.com/casid/jte-intellij

However, I've spent more time on the IntelliJ plugin than on jte itself. Writing that plugin was really a pain :-D

I fear there isn't much code to be reused either, since everything is custom Jetbrains APIs.

**Comment by renannprado** [comment]
I've never developed a plugin for IntelliJ, but if it supports the [language server protocol](https://microsoft.github.io/language-server-protocol/) you might have the chance to _kill two flies with one clap_.

That being said... I'd still say that using VSCode for Java development is a bit of a niche still.

**Comment by casid** [comment]
Right now there's no plan / resources to do so.
