### ISSUE TITLE
layout as alternative to tag.layout

### ISSUE THREAD

**Issue by Fender123** [casid/jte#56]
the intellij plugin suggests me to use `@layout.*` additionally to `@tag.*` 
Moving my layout from tags to layout and updating the code is working.
But I can't find anything about in the documentation.
Is it safe to use this? Are you planning to remove it? Or is it just missing documentation?

**Comment by casid** [comment]
@Fender123 oh thanks for pointing that out.

Yes, this is currently supported. In the early jte days layouts and tags where handled differently. With the introduction of content blogs, both can do the same thing.

I think it is nice to have support for both, to help to structure it semantically a little bit better. In my personal projects I use this structure, too. I have to admit, that I changed the example on the front page to use a tag, because there are a lot more tags than layouts. But the documentation certainly needs improvements there.

What do you think? Does it help your project structure to have support for both tag and layout?

**Comment by Fender123** [comment]
Absolutely.
Keeping layouts and tags apart is a good idea.
That's why I asked if it is safe to use 😉

**Comment by casid** [comment]
@Fender123 I've updated the documentation with a `layout` section.
