### ISSUE TITLE
Idea: pluggable language/parser support for templates

### ISSUE THREAD

**Issue by davidkron** [casid/jte#57]
First I want to congratulate you on open sourcing your library. It is great to see some new kids on the Java template front. I especially like that you designed and implemented this library with first-class IntelliJ integration.

Even though the library is great, my subjective downside of the library is definitely the verboseness, which is not your fault but due to Java itself and your philosophy (which I like) of not inventing another expression language. This brought me to the idea if it would be possible to make the template language "pluggable". I think Razor in the .NET world does something like this by allowing the template code to be either C# or VB. For example Kotlin would be a great addition for templates as it is type-safe aswell, but has some nice syntactic sugar that would reduce some cognitive load in templates. Something like this would surely be a unique selling point that no other template engine in the Java world could offer.

I don't know if this would be even technically possible or how hard and time consuming it would be to implement this.
I just wanted to place the idea here, so feel free to just close the issue if this is nothing you would consider in the future or it is just not possible.

**Comment by casid** [comment]
Hey @davidkron, thanks for the heads-up!

I actually did a kotlin experiment a while ago on this branch: https://github.com/casid/jte/tree/kotlin-experiment

Adjusting the template engine to work with kotlin was actually pretty straight forward. The problem was, that the IntelliJ plugin did not work very well. Unfortunately JetBrains wasn't really helpful on that front either so far:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008216139-Is-MultiHostInjector-the-right-approach-for-a-Kotlin-based-template-engine-plugin-

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008349720-Kotlin-references-in-MultiHostInjector-are-not-working-correctly

**Comment by casid** [comment]
@davidkron I couldn't resist to give your idea a try today.

I got the basic template functinality working and added a test for kotlin templates: https://github.com/casid/jte/blob/feac2204f30c416f2666599d773e95b458d0ff86/jte/src/test/java/gg/jte/TemplateEngine_KotlinTest.java

On this branch, templates with .kte extension are generated with the Kotlin code generator and if there are kte templates present, the kotlin compiler is used instead of the Java compiler.

I split a few classes and could surprisingly clean separate a java and a kotlin package.

https://github.com/casid/jte/tree/kotlin-support/jte/src/main/java/gg/jte/compiler/java
https://github.com/casid/jte/tree/kotlin-support/jte/src/main/java/gg/jte/compiler/kotlin

There are still a few todos left:
- I think the kotlin package should be moved to a separate module, so there isn't a dependency to the kotlin compiler per default
- I have no idea if it is possible or even should be possible to support mixing jte/kte templates in one project.
- Port the remaining tests to ensure that all features (like HTML QoL) work with Kotlin
- Finally, the IntelliJ plugin. Sigh. Maybe I need to have another look at it with the latest IntelliJ version. But I think it should be possible that the plugin can handle both .jte and .kte files!

**Comment by casid** [comment]
@davidkron JetBrains just approve the first plugin with support for *.kte templates :-)

https://plugins.jetbrains.com/plugin/14521-jte
