### ISSUE TITLE
[Proposal] Smarter casts in tags/layouts

### ISSUE THREAD

**Issue by rferreira** [casid/jte#66]
When a parameter of type Object is passed into a tag/layout it should automatically be cast to the expected param type; today the IntelliJ plugin believes the cast is unnecessary but it is not and without it the jte compiler throws the error shown below: **error: incompatible types: Object cannot be converted to User**

Proposal: before erroring out, JTE should attempt to cast the parameter to the expected type this will make the template more concise and easier to write. 

```java
@import com.uvasoftware.noni.web.model.user.User
@param java.util.Map<String, Object> context

@layout.private(title = "overview", user = (User) context.get("user"), content = @`
  <h1>Overview Page</h1>
`)
```
```
/Users/rafael/Dev/uvasoftware/noni/noni-web/target/jte-classes/gg/jte/generated/ondemand/pages/account/JteoverviewGenerated.java:11: error: incompatible types: Object cannot be converted to User
		}, context.get("user"));
		              ^
Note: /Users/rafael/Dev/uvasoftware/noni/noni-web/target/jte-classes/gg/jte/generated/ondemand/pages/account/JteoverviewGenerated.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error

gg.jte.TemplateException: Failed to compile template, error at pages/account/overview.jte:5
/Users/rafael/Dev/uvasoftware/noni/noni-web/target/jte-classes/gg/jte/generated/ondemand/pages/account/JteoverviewGenerated.java:11: error: incompatible types: Object cannot be converted to User
		}, context.get("user"));
		              ^
Note: /Users/rafael/Dev/uvasoftware/noni/noni-web/target/jte-classes/gg/jte/generated/ondemand/pages/account/JteoverviewGenerated.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error

	at gg.jte.compiler.java.JavaClassCompiler.runCompiler(JavaClassCompiler.java:46)
	at gg.jte.compiler.java.JavaClassCompiler.compile(JavaClassCompiler.java:34)
	at gg.jte.compiler.TemplateCompiler.precompile(TemplateCompiler.java:82)
	at gg.jte.compiler.TemplateCompiler.load(TemplateCompiler.java:40)
	at gg.jte.TemplateEngine.resolveTemplate(TemplateEngine.java:364)
	at gg.jte.TemplateEngine.hasTemplate(TemplateEngine.java:294)
```

layout: 
```java
@import com.acme.User
@import gg.jte.Content

@param User user
@param Content content

${content}
```

**Comment by rferreira** [comment]
I'll see if I can whip up a POC PR for the above

**Comment by casid** [comment]
I think this won't be easy to do and increase the template generation complexity.

Currently there is some "type" info stored for each parameter, but it is hard to use that outside of the defining template, without considering imports.

For example:

```
@import foo.User
@param User
${user.getName()}
```

and calling it from here

```
@import bar.User
@param User barUser
@param Map<String, Object> context
@tag.example(context.get("user"))
```

The cast here would need to be `(foo.User)context.get("user")`.

I haven't experienced this problem in any of my jte projects yet. Using context maps wastes a lot of jte's potential, cause you end up with String based lookups without autocomplete :-)

What you could also do:

```
public class OverviewPageContext {
   public User getUser() {
       // ....
   }
}
```

And pass an instance of that context to your template.

```
@import com.uvasoftware.noni.web.model.OverviewPageContext
@param OverviewPageContext context

@layout.private(title = "overview", user = context.getUser(), content = @`
  <h1>Overview Page</h1>
`)
```

Currently the IDEA plugin isn't as smart about tag/layout params as I would like it to be. I think that'd be the better fix, to show if a tag/layout is called with the wrong type.

As if the above example would be this:

```
@import com.uvasoftware.noni.web.model.OverviewPageContext
@param OverviewPageContext context

@layout.private(title = "overview", user = context.getContentType(), content = @`
  <h1>Overview Page</h1>
`)
```

I'd rather have the IDEA plugin show an error that a user is expected not a content type, instead of no error and a magic cast that fails somewhere behind the scenes anyway.
