### ISSUE TITLE
Question: does JTE perform removal of logical white space?

### ISSUE THREAD

**Issue by pmlopes** [casid/jte#69]
Say for example I've this template:

```
@import java.util.*
@param List<Map<String, String>> fortunes
<!DOCTYPE html>
<html>
<head><title>Fortunes</title></head>
<body>
<table>
  <tr>
    <th>id</th>
    <th>message</th>
  </tr>
  @for(Map<String, String> fortune : fortunes)
    <tr>
      <td>$unsafe{fortune.get("id")}</td>
      <td>${fortune.get("message")}</td>
    </tr>
  @endfor
</table>
</body>
</html>
```

Is there a way to ensure that new lines and spaces between html tags are removed? I know this is very html specific and would probably require some validation.

**Comment by casid** [comment]
@pmlopes there's a property on `TemplateEngine` called `trimControlStructures` that can be enabled. This ensures that all template language indentations are removed in the final output (this is done at compile time, so pretty fast 👍). So in your example template, the whitespaces and indentations caused by the for loop would be removed in the final output.

I still have this open issue though: https://github.com/casid/jte/issues/10
This would be an HTML specific setting, that compresses all unrequired whitespaces from the output. To properly implement that the engine would need to know the CSS classes that are used. The default could be that `<pre>` tags are left unchanged, but that style could potentially be on any tag.
