### ISSUE TITLE
Cannot render a nested class Object

### ISSUE THREAD

**Issue by benjamin-thomas** [casid/jte#73]
Hello,

I'm evaluating the [javalite](https://javalite.io/) libraries, and would like to understand if using `jte` with its `activeweb` lib is a good idea (great job with jte btw).

I've hit what seems to be a bug in jte. Could you have a look at my repo here ?

https://github.com/benjamin-thomas/javalite-jte-demo/blob/0d1e6f77dd4675bcd7b83b9aeb19041389b453c9/src/main/java/app/controllers/Hello2Controller.java#L22

I've documented the failure in the README:

```
Failed to render hello2/hello.jte,
    type mismatch for parameter: 
        Expected 
            app.controllers.HelloController$HelloPage 
        got 
            app.controllers.HelloController$HelloPage
```

The dollar sign looks suspicious to me, but I'm not a java dev so hope I'm not doing something stupid.

I want to use an inner class because `activeweb` has a dev feature where the controller class gets recompiled on page refresh.

So it's a sensible place to put the page object, at least while iterating.

Thanks ;)

**Comment by casid** [comment]
@benjamin-thomas this looks like a class loading error.

jte uses the current thread's context class loader, when no class loader is specified.

Can you try to check what classloader javalite uses? If you temporarily print this in your controller, just before invoking the template engine?
```java
System.out.println(Thread.currentThread().getContextClassLoader());
System.out.println(getClass().getClassLoader());
```

There's a factory method in TemplateEngine that accepts a class loader as argument. My guess would be that you need to pass the correct one from javalite there, to fix this issue.

Also, I just noted that you create a new `TemplateEngine` instance in your `JTE#render` method. I would recommend to create the engine only once at startup (maybe as a singleton bean). Otherwise the performance gonna be pretty bad :-)

**Comment by benjamin-thomas** [comment]
Thanks that was exactly it! 

Using the dev hot reload feature meant a could see a different `getClass().getClassLoader()` object on every request indeed.

So passing it along to the factory method did the trick, sorry this wasn't related to jte at all.

> Also, I just noted that you create a new TemplateEngine instance in your JTE#render method. I would recommend to create the engine only once at startup (maybe as a singleton bean). Otherwise the performance gonna be pretty bad :-)

Thanks for the heads up ;)
